# Generated by Django 6.1.1 on 2026-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_question_question_type_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True or False'), ('identification', 'Identification'), ('enumeration', 'Enumeration')], default='multiple_choice', max_length=30),
        ),
    ]
