# Generated by Django 6.1.1 on 2026-09-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_status_userprofile_bonus_course_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='review_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
    ]
